# Generated by Django 4.0.6 on 2022-07-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.SlugField(default='Unknown', max_length=20),
        ),
    ]
